-- /helgon data-driven ur saints (undvik hårdkodat). Display-kolumner + backfill av 11 hub-helgon.
-- Applicerad i prod via MCP (repo-spegling). 2026-08-06.
ALTER TABLE public.saints
  ADD COLUMN IF NOT EXISTS life_line text, ADD COLUMN IF NOT EXISTS note text,
  ADD COLUMN IF NOT EXISTS place_label text, ADD COLUMN IF NOT EXISTS map_href text,
  ADD COLUMN IF NOT EXISTS link_label text, ADD COLUMN IF NOT EXISTS sort_year int,
  ADD COLUMN IF NOT EXISTS show_on_hub boolean NOT NULL DEFAULT false;
-- Backfill (data ur prod; kurerade noter + kart-länkar för de 11 hub-helgonen):
UPDATE public.saints SET show_on_hub=true, sort_year=1020, life_line='Missionsbiskop, 1000-tal', note='Knuten till Växjö och kristnandet av Småland/Värend. Enligt legenden döpte han Olof Skötkonung i Husaby — en legenduppgift, inte ett fast belägg.', place_label='Husaby, Västergötland — dopplatsen (kungsgård & källa)', map_href='/explore?center=58.5667,13.2833&zoom=14', link_label='Visa på kartan →' WHERE code='sigfrid';
UPDATE public.saints SET show_on_hub=true, sort_year=1030, life_line='Olav Haraldsson, † Stiklestad 1030', note='Norges kung och sjöfararnas skyddshelgon. En av Nordens starkaste kulter — kyrkor, offerkällor och pilgrimsvägar mot graven i Nidaros. Egen sida med kyrkoruin, Mälaren-seglingen och källkritik.', place_label=NULL, map_href='/sv/sankt-olof', link_label='Läs mer →' WHERE code='olof';
UPDATE public.saints SET show_on_hub=true, sort_year=1080, life_line='Engelsk missionsbiskop, martyr, 1000-tal', note='Verkade i Södermanland; enligt traditionen stenad vid Strängnäs/Tuna. Gav namn åt Eskilstuna.', place_label=NULL, map_href=NULL, link_label=NULL WHERE code='eskil';
UPDATE public.saints SET show_on_hub=true, sort_year=1086, life_line='Knut den helige (Knut IV av Danmark), † 1086', note='Danmarks skyddshelgon, populär vid Östersjön. Vid Gråborg på Öland ligger ruinen av det kapell som bar hans namn — en vallfarts- och marknadsplats invid en av öns stora fornborgar.', place_label='Sankt Knuts kapell vid Gråborg, Öland (ruin, 1100-tal–ca 1560)', map_href='/explore?center=56.66792,16.60133&zoom=14', link_label='Visa på kartan →' WHERE code='knut';
UPDATE public.saints SET show_on_hub=true, sort_year=1100, life_line='Missionär, 1000-/1100-tal', note='Knuten till kristnandet av Västmanland; vördad vid Munktorp.', place_label=NULL, map_href=NULL, link_label=NULL WHERE code='david_munktorp';
UPDATE public.saints SET show_on_hub=true, sort_year=1117, life_line='ca 1075 – omkring 1117', note='Tälje-bornas (Södertälje) skyddshelgon. KÄLLKRITIK: historiciteten trolig men osäker (äldsta källor 1400-tal); drottning-/gemåluppgifterna (Inge d.ä. vs d.y.) omtvistade; fadersuppgiften "kung Halsten" anses orimlig. Enligt traditionen grundade hon Södertälje sockenkyrka.', place_label='Södertälje (Tälje)', map_href='/explore?searchQuery=S%C3%B6dert%C3%A4lje', link_label='Visa på kartan →' WHERE code='ragnhild_talje';
UPDATE public.saints SET show_on_hub=true, sort_year=1120, life_line='Svensk lekmannamissionär, † ca 1120', note='Sörmländsk helgonkult; gav namn åt Botkyrka. Enligt legenden dräpt av en frigiven träl.', place_label=NULL, map_href=NULL, link_label=NULL WHERE code='botvid';
UPDATE public.saints SET show_on_hub=true, sort_year=1155, life_line='1100-tal', note='Västgötsk helgonkvinna, vördad i Skövde; en av få inhemska kvinnliga helgon före Birgitta.', place_label=NULL, map_href=NULL, link_label=NULL WHERE code='helena';
UPDATE public.saints SET show_on_hub=true, sort_year=1160, life_line='Erik Jedvardsson, kung, † enligt traditionen 1160', note='Sveriges skyddshelgon. Enligt Erikslegenden (nedtecknad senare) dräpt i Uppsala; hans reliker vilar i Uppsala domkyrka. Legendens historiska kärna är omdiskuterad — märks som legend.', place_label=NULL, map_href=NULL, link_label=NULL WHERE code='erik';
UPDATE public.saints SET show_on_hub=true, sort_year=1373, life_line='Birgitta Birgersdotter, ca 1303–1373', note='Grundare av Birgittinorden och Vadstena kloster; kanoniserad 1391. Ett av Europas skyddshelgon. Hennes uppenbarelser (Revelationes) fick vidsträckt spridning. (Folkligt "S:t Britta".)', place_label='Birgittakyrkan i Kalmar (omtalad 1440-talet; Gamla stan — approx.)', map_href='/explore?center=56.65972,16.34822&zoom=16', link_label='Visa på kartan →' WHERE code='birgitta';
UPDATE public.saints SET show_on_hub=true, sort_year=1450, life_line='Jungfru Marias mor, Jesu mormor (legendarisk)', note='Ett av senmedeltidens mest populära helgon — skyddshelgon för blivande mödrar och bergsmän. KÄLLKRITIK: Anna nämns inte i Bibeln; legenden kommer ur den apokryfa Jakobs protoevangelium (100-tal). Motiv "Anna själv-tredje". Firas 9 december. Källa: Historiska museet.', place_label='S:t Annas skärgård, Östergötland', map_href=NULL, link_label=NULL WHERE code='anna';
