-- 7 verkliga vikingaföremål ur SHM:s utställning "Vikingarnas värld" (källa: Statens historiska museum,
-- foton CC-BY 4.0). Fakta paraphraserade, ej verbatim SHM-text. Tolkningar (Oden/Lindby, völva) märkta.
-- INGA påhittade koordinater/inventarienr — lat/lng null (find_place som text, verifieras separat).
-- Applicerad i prod via MCP; denna fil = repo-spegling. 2026-08-07.
insert into public.museum_objects (name, description, category, material, find_landscape, find_socken, find_kommun, find_place, period, period_start, period_end, context, source, source_url, attribution)
select * from (values
  ('Buddha från Helgö', 'Gjuten bronsstatyett av Buddha på en tron formad som dubbel lotusblomma, med "tredje ögat" i pannan. Tillverkad ca 400–500-tal, sannolikt i Swatdalen (nuv. gränstrakt Afghanistan/Pakistan). Kom till Helgö under vendel-/vikingatid; hittad vid utgrävning 1956. Vittnar om fjärrkontakter.', 'figurin (import)', 'brons', 'Uppland', NULL, 'Ekerö', 'Helgö', '400–500-tal (tillverkn.); vendel-/vikingatida fyndkontext', 470, 530, 'SHM, utställningen Vikingarnas värld, monter 07', 'Statens historiska museum (SHM)', 'https://historiska.se', 'Foto: Erik Lernestål, SHM, CC-BY 4.0'),
  ('Skyddshalsbandet från Birka', 'Halsband ur en kammargrav (900-tal) vid handelsplatsen Birka; låg på den gravlagda kvinnans bröst. Pärlor av bergkristall och karneol från Kaukasus samt 15 hängen — ett föreställer en kubbstol, förknippad med spådom. TOLKNING: kan tyda på att kvinnan var en völva (sierska).', 'smycke/dräkt', 'bergkristall, karneol, metall', 'Uppland', 'Adelsö', 'Ekerö', 'Birka (Björkö)', 'vikingatid (900-tal)', 850, 950, 'SHM, utställningen Vikingarnas värld, monter 04', 'Statens historiska museum (SHM)', 'https://historiska.se', 'Foto: Ola Myrin, SHM, CC-BY 4.0'),
  ('Oden från Lindby', 'Gjuten bronsfigur av en man med uppåtvridna mustascher, spetsigt hakskägg och spetsig huvudbonad (ev. hjälm), knälång rock och bälte. Nithål under fötterna → var monterad på en bas. TOLKNING: det skadade/deformerade ena ögat har tolkats som att figuren föreställer Oden (som offrade ett öga i Mimers brunn); andra menar att skadan uppstod vid gjutningen — osäkert. Länge kallad "Oden från Lindby".', 'figurin', 'brons', 'Skåne', NULL, NULL, 'Lindby', 'vikingatid', 800, 1050, 'SHM, utställningen Vikingarnas värld, monter 57', 'Statens historiska museum (SHM)', 'https://historiska.se', 'Foto: Ola Myrin, SHM, CC-BY 4.0'),
  ('Klintastaven', 'Rikt dekorerad järnstav med detaljer i koppar och brons, 82 cm i fyndskick (nedre delen avbruten → ursprungligen längre), böjd på flera ställen — kanske avsiktligt innan den lades snett i gravdeponin. TOLKNING: völvestav (sejd/spådom).', 'stav (kultföremål)', 'järn, koppar, brons', 'Öland', NULL, NULL, 'Klinta', 'vikingatid', 900, 1000, 'SHM, utställningen Vikingarnas värld, monter 68', 'Statens historiska museum (SHM)', 'https://historiska.se', 'Foto: Jens Mohr, SHM, CC-BY 4.0'),
  ('Söderalaflöjeln', 'Förgylld bronsflöjel dekorerad i Ringerikestil, ursprungligen på Söderala kyrkas torn i Hälsingland; kom till museet 1917. Består av stora och små bronsplåtar med en djurfigur på överkanten; hål på undersidan bar frit hängande löv (nu saknade).', 'vindflöjel', 'förgylld brons', 'Hälsingland', 'Söderala', NULL, 'Söderala kyrka', 'sen vikingatid (Ringerikestil, ca 1000–1050)', 1000, 1050, 'SHM, utställningen Vikingarnas värld, monter 78', 'Statens historiska museum (SHM)', 'https://historiska.se', 'Foto: Ola Myrin, SHM, CC-BY 4.0'),
  ('Mästermyrkistan', 'Unik verktygskista av ek, 90 cm lång och 30 cm hög, med järnlås, svagt välvt lock av plankor och laxade hörn. Från arkeologiskt fynd i Mästermyr, Silte socken, Gotland. Nästan oskadd trots att den plöjts upp av en traktor.', 'verktygskista', 'ek, järn', 'Gotland', 'Silte', NULL, 'Mästermyr', 'vikingatid', 900, 1050, 'SHM, utställningen Vikingarnas värld, monter 24', 'Statens historiska museum (SHM)', 'https://historiska.se', 'Foto: Ola Myrin, SHM, CC-BY 4.0'),
  ('Vårbyskatten', 'Silverskatt med föremål från hela dåtidens kända värld — skandinaviskt, västligt, östligt och västslaviskt ursprung. Innehåller både manligt och kvinnligt kodade smycken och beslag.', 'silverskatt/depå', 'silver', 'Södermanland', NULL, 'Huddinge', 'Vårby', 'vikingatid', 900, 1000, 'SHM, utställningen Vikingarnas värld, monter 02', 'Statens historiska museum (SHM)', 'https://historiska.se', 'Foto: Jens Mohr, SHM, CC-BY 4.0')
) as v(name, description, category, material, find_landscape, find_socken, find_kommun, find_place, period, period_start, period_end, context, source, source_url, attribution)
where not exists (select 1 from public.museum_objects m where m.name = v.name);
