-- Kunglig osteologi (data): Magnus Ladulås familjegrav i Riddarholmskyrkan
-- (gravtumban i koret; Olsson/Fürst 1915–16, Vretemark 2011) och Birger Jarl-graven
-- i Varnhems klosterkyrka (öppnad 2002). Individuella osteologiska profiler.
-- Idempotent på sample_id. king_id sätts bara för identifierade regenter.

INSERT INTO public.genetic_individuals
  (sample_id, individual_label, king_id, site_id, archaeological_sex, age, stature_cm,
   pathology, dental_status, grave_number, burial_context, period_from, period_to, source)
SELECT v.sample_id, v.label,
       (SELECT id FROM public.historical_kings hk WHERE hk.name ILIKE v.king_pat LIMIT 1),
       (SELECT id FROM public.archaeological_sites s WHERE s.name = v.site LIMIT 1),
       v.sex, v.age, v.stature, v.pathology, v.dental, v.grave, v.context, v.pfrom, v.pto, v.source
FROM (VALUES
  -- Riddarholmskyrkan — Magnus Ladulås familjegrav (gravtumban), Vretemark 2011 / Fürst 1916
  ('RIDD-tumban-sk1', 'Magnus Ladulås (skelett 1)', 'Magnus Ladul%', 'Riddarholmskyrkan',
   'male', '45–60 år', 185::numeric,
   'Kraftiga pålagringar på båda skenbenen och armbågsbenen — resultat av långvarig sjukdom.',
   'Har tappat alla tänder i livet (kopplat till hans allmänna sjukdomstillstånd).',
   'Gravtumban, skelett 1',
   'Magnus Ladulås familjegrav i Riddarholmskyrkans kor; öppnad 1915 (Martin Olsson/Carl-Magnus Fürst) och 2011 (Maria Vretemark). Graven återanvänd minst sex gånger. Magnus valde själv gravplatsen i gråmunkarnas kloster.',
   1240, 1290, 'Osteologi: Maria Vretemark 2011 / C-M Fürst 1916. Riddarholmskyrkan.'),
  ('RIDD-tumban-sk2', 'Junker Magnus Birgersson (skelett 2)', NULL, 'Riddarholmskyrkan',
   'male', '20–30 år', 176::numeric, NULL,
   'Svagt slitage; tre av fyra sexårständer tappade pga karies, troligen redan i tonåren.',
   'Gravtumban, skelett 2',
   'Barnbarn och namne till Magnus Ladulås; född i Stockholm sept 1300, tronföljare 1304, halshuggen på Helgeandsholmen 27 okt 1320 efter Nyköpings gästabud.',
   1300, 1320, 'Osteologi: Maria Vretemark 2011 / C-M Fürst 1916. Riddarholmskyrkan.'),
  ('RIDD-tumban-sk3', 'Valdemar Eriksson (skelett 3)', NULL, 'Riddarholmskyrkan',
   'male', '45–60 år', 190::numeric,
   'Läkt fraktur på vänster överarmsben; mycket kraftigt skelett från en storvuxen person.', NULL,
   'Gravtumban, skelett 3',
   'Sonson till exkung Valdemar (Magnus bror); i källorna 1345–1368.',
   1345, 1368, 'Osteologi: Maria Vretemark 2011 / C-M Fürst 1916. Riddarholmskyrkan.'),
  ('RIDD-tumban-sk4', 'Erik Valdemarsson (skelett 4)', NULL, 'Riddarholmskyrkan',
   'male', 'över 60 år', 174::numeric,
   'Spår av bihåleinflammation samt viss tendens till benskörhet (osteoporos).', NULL,
   'Gravtumban, skelett 4',
   'Son till exkung Valdemar; född 1272, riksråd under Magnus Erikssons förmyndarskap, död 1327–33.',
   1272, 1333, 'Osteologi: Maria Vretemark 2011 / C-M Fürst 1916. Riddarholmskyrkan.'),
  ('RIDD-tumban-sk5', 'Drottning Helvig av Holstein (skelett 5)', NULL, 'Riddarholmskyrkan',
   'female', 'över 60 år', 161::numeric,
   'Höger lårben skadat i leden — tillväxthämmat, 2 cm kortare, ledkulan felläkt (18–20 års ålder), kraftig artros, låghalt. Osteoporos. Kraniet avsiktligt lindat/deformerat i unga år (nordtysk/holländsk sed).',
   'Visdomständerna förlorade under livet.',
   'Gravtumban, skelett 5',
   'Grevdotter från Holstein; gift med Magnus Ladulås i Kalmar 1276 (minst sex barn); född 1255–60, död 1324–26.',
   1255, 1326, 'Osteologi: Maria Vretemark 2011 / C-M Fürst 1916. Riddarholmskyrkan.'),
  ('RIDD-tumban-sk6', 'Rikissa Magnusdotter (skelett 6)', NULL, 'Riddarholmskyrkan',
   'female', '35–50 år', 171::numeric,
   'Möjligen avsiktligt deformerat kranium.',
   'Svagt slitage och en del karies.',
   'Gravtumban, skelett 6',
   'Dotter till Magnus Ladulås och Helvig; bortlovad till Sancta Clara kloster vid sex års ålder, dess första abbedissa 1335; född 1285–87, död 17 dec 1348.',
   1285, 1348, 'Osteologi: Maria Vretemark 2011 / C-M Fürst 1916. Riddarholmskyrkan.'),
  ('RIDD-tumban-sk7', 'Erik Valdemarsson d.y. (skelett 7)', NULL, 'Riddarholmskyrkan',
   'male', '35–50 år', 175::numeric,
   'Emaljhypoplasier på framtänderna — troligen spår av en kraftig febersjukdom under barndomen (ej rakitis).',
   'Fina, jämna tänder utan karies.',
   'Gravtumban, skelett 7',
   'Sonsonson till exkung Valdemar; i källorna 1375, död 1388 — med honom dog Bjälboätten (folkungaätten) ut på svärdssidan.',
   1375, 1388, 'Osteologi: Maria Vretemark 2011 / C-M Fürst 1916. Riddarholmskyrkan.'),
  ('RIDD-tumban-barn1', 'Barn (~2,5 år) — Magnus Ladulås familjegrav', NULL, 'Riddarholmskyrkan',
   NULL, '~2,5 år', NULL::numeric, NULL, NULL, 'Gravtumban, kista 8',
   'Barnben ur familjegraven (kista 8).', NULL, NULL, 'Osteologi: Maria Vretemark 2011. Riddarholmskyrkan.'),
  ('RIDD-tumban-barn2', 'Barn (~10 år) — Magnus Ladulås familjegrav', NULL, 'Riddarholmskyrkan',
   NULL, '~10 år', NULL::numeric, NULL, NULL, 'Gravtumban, kista 8',
   'Barnben ur familjegraven (kista 8).', NULL, NULL, 'Osteologi: Maria Vretemark 2011. Riddarholmskyrkan.'),
  -- Varnhems klosterkyrka — Birger Jarl-graven, öppnad 2002 (osteologi + DNA bekräftade)
  ('VARNHEM-BirgerJarl', 'Birger Jarl (Birger Magnusson)', 'Birger Jarl', 'Varnhem',
   'male', 'äldre man', NULL::numeric,
   'Kraniet uppvisade markanta likheter med stiftarbilden av Birger i kyrkan.', NULL,
   'Upphöjda graven',
   'Stockholms grundare; valde Varnhems kloster som sista viloplats. Graven återfunnen 1920 (tre skelett), öppnad på nytt 2002 — osteologi + DNA bekräftade identifieringen. Död 1266.',
   1210, 1266, 'Gravöppning 2002; osteologi + DNA. Varnhems klosterkyrka.'),
  ('VARNHEM-Mechtild', 'Mechtild (Matilda) av Holstein — Birger Jarls 2:a hustru', NULL, 'Varnhem',
   'female', NULL, NULL::numeric, NULL, NULL, 'Upphöjda graven',
   'Birger Jarls andra hustru; i den upphöjda graven i Varnhems klosterkyrka (porträttsten: kvinna + två män).',
   NULL, 1288, 'Gravöppning 2002; osteologi + DNA. Varnhems klosterkyrka.'),
  ('VARNHEM-HertigErik', 'Hertig Erik — Birger Jarls son (första äktenskapet)', NULL, 'Varnhem',
   'male', NULL, NULL::numeric, NULL, NULL, 'Upphöjda graven',
   'Son till Birger Jarl ur första äktenskapet; i Varnhem-graven.',
   NULL, NULL, 'Gravöppning 2002; osteologi + DNA. Varnhems klosterkyrka.')
) AS v(sample_id, label, king_pat, site, sex, age, stature, pathology, dental, grave, context, pfrom, pto, source)
WHERE NOT EXISTS (SELECT 1 FROM public.genetic_individuals g WHERE g.sample_id = v.sample_id);
