-- Ledung-paragrafer BATCH 2 → source_texts. Framtaget av filolog-agenten, verifierat av orkestrator.
-- Källkritik: Södermannalagen reglerar ledung (Konungabalken flock X + XI). Skånelagen har INGEN
-- ledings-organisation — endast EN fiskal notis (kap. 74); organisationen (havne/styrismand) hör hemma
-- i Kong Valdemars Jordebog, ej i lagtexten. Östgötalagen: ledung EJ reglerad i bevarad text (negativfynd).
-- COPYRIGHT: grundtext = PD (Schlyter/SSGL 1827–1877; digital verbatim ur Fornsvenska textbanken, LU).
--   Översättning = Viking Age EGEN. Holmbäck & Wessén EJ använd/citerad. Font-ligaturen ﬁ→Þ normaliserad.
-- Kollationerings-förbehåll (tryckt SSGL-sida) noteras i norse_source (ej blockerande för kärnfakta).

-- 0) Sätt PD-rights FÖRST (copyright-guard-triggern blockerar verbatim grundtext om rights=unknown).
-- Grundtext/edition är PD (Schlyter SSGL 1827–1877). Skånelagen redan PD.
update public.historical_sources set rights='public_domain', updated_at=now()
where title in ('Södermannalagen','Östgötalagen') and rights <> 'public_domain';

-- 1) Poster MED verbatim grundtext (SdmL flock X, SdmL flock XI, SkL kap. 74).
insert into public.source_texts
  (source_id, stanza_no, section_label, original_norse, translation_sv, translation_en, norse_source, sv_source, en_source, translation_kind)
select hs.id, base.mx + v.ord, v.section_label, v.norse, v.sv, v.en, v.norse_source,
       'Viking Age egen översättning (fornspråk→nusvenska)', 'Viking Age own translation', 'egen'
from (values
  ('Södermannalagen', 1,
   'Konungabalken (Kunungx balkær), flock X — "Vm kununx leþung"',
   'Vm kununxleþung. .X.
Nv biuþer kununger lyð oc leðung vt. þa scal matu til skips bæræ. þen scal fara þær ælzter ær a færð. Delæ mæn vm ferþenæ. þa fari þen hamnamæn til witnæ. Saar man i by annæn æn han boor i. oc sar attung fullan. fari swa opta han sum þen man by sar halwan. Sar han minnæ æn attung. bærin þa saman flere. þær til attunger ær fulder. fari siþan þen leþæ fyrstæ bær luter til. vm alla kununx vt gierþir sculu bönder .XIIII. natum fyrræ buð fa æn þe hana göræ sculu. vtan kununx fall warþi at han fyrræ þorwe.
§. 1. ¶ Hwar sum dirwis til forna hamnu rywæ. vtan með styræmanz raþe oc alz skipalags. böte III. marker. I. kunungi. andra skipalaghi. þriþiu malseghanda.
§. 2. Siter hamna quer vm vt gierþir kununx. böte III. marker. Siter quer annur oc þriþiæ. böte III. marker hwart þeræ. oc meþ vt gierþir. wari oc ei bot þy mere vtan alder fiarþunger falli. Fællir siþan fiarþungher fuller. böte X. marker. Fellir halft skiplagh. böte XX. marker. Fellir skiplagh alt. böte XL. marker.
§. 3. ¶ Nu sculu kununx vt gierþir in takas. þa scal þer styreman af skipalaghi firi wara. wita hwar ræt gör eller ei. Kan inteckiu man nocrum sac wilia giwa at han hawer ei fult giort. wæri þen sic með styremanni sinum. oc twem wiþer waro mannum. oc XII. manna witnum. af fiarþungi þem sama sum han ær af. at han hawer fult giort. Engin ma lagh firi kununx vt gierþir ganga. ei hamna eller fiærþunger. ei halft hundare. oc æn siþær helt.',
   'Om konungens ledung. Kap. X.
Nu bjuder konungen ut folk (ledungsuppbåd) och ledung. Då skall man bära matförråd till skeppet. Den skall fara (ut) som är äldst på färden. Tvistar män om färden, då må hamnamannen fara med som vittne. Bor en man i en annan by än den han (egentligen) hör till och besitter en hel attung, fare (ut) lika ofta som den man i vars by han besitter hälften. Besitter han mindre än en attung, slå då flera samman till dess en full attung nås; fare sedan den på vilken lotten först faller. Om alla konungens utgärder skola bönderna få bud fjorton nätter i förväg innan de skall fullgöra dem — utom (då) ett kungens anfall (nödläge) gör att han behöver dem tidigare.
§1. Var och en som dristar sig att riva ned en gammal hamna utan styresmannens råd och hela skeppslagets (samtycke), böte tre mark: en till konungen, en till skeppslaget, en tredje till målsäganden.
§2. Sitter en hamna stilla (försummar) vid konungens utgärder, böte tre mark. Försummar den en andra och tredje gång, böte tre mark var gång jämte utgärderna; och böterna blir icke större än så, om icke hela fjärdingen brister. Brister sedan en hel fjärding, böte tio mark. Brister ett halvt skeppslag, tjugo mark. Brister hela skeppslaget, fyrtio mark.
§3. Nu skola konungens utgärder tas upp. Då skall skeppslagets styresman vara närvarande för att veta vem som gör rätt eller ej. Vill någon anklaga en man för att han icke fullgjort (sin del), värje han sig med sin styresman och två grannar (vittnesnärvarande) och tolv mäns vittnesmål ur samma fjärding han själv tillhör, (om) att han har fullgjort. Ingen må värja sig med lag mot konungens utgärder — varken en hamna eller en fjärding, icke ett halvt hundare, och än mindre ett helt.',
   'On the king''s ledung (naval levy). Ch. X.
Now the king summons the levy and the ledung. Then provisions shall be carried to the ship. He who is most senior on the expedition shall go. If men dispute about the expedition, the hamna-man (head of the oar-district) shall go along as witness. If a man dwells in a village other than his own and holds a full attung, he shall go as often as the man in whose village he holds a half-share. If he holds less than an attung, several shall be joined until a full attung is reached; thereafter he goes upon whom the lot first falls. For all the king''s renders the farmers shall receive fourteen nights'' notice before they must render them, unless a royal attack (emergency) requires them sooner.
§1. Whoever dares to break down an old hamna without the steersman''s counsel and the whole ship-district''s consent shall pay three marks: one to the king, one to the ship-district, a third to the plaintiff.
§2. If a hamna defaults at the king''s renders, it pays three marks; a second and third default, three marks each, plus the renders; and the fine grows no larger unless a whole quarter (fjärding) defaults. A whole quarter in default: ten marks. Half a ship-district: twenty marks. A whole ship-district: forty marks.
§3. Now the king''s renders are to be collected. The ship-district''s steersman shall be present to know who renders rightly. If anyone would charge a man with not rendering in full, let him clear himself with his steersman, two neighbours, and the oath of twelve men from his own quarter, that he has rendered in full. No one may plead law against the king''s renders — neither a hamna, a quarter, half a hundred, still less a whole one.',
   'Schlyter, SSGL band IV (Södermannalagen), 1838 — Konungabalken, flock X ("Vm kununx leþung"). Digital verbatim-text: Fornsvenska textbanken (Holm B 53 / SSGL 4), nordlund.lu.se/texter/aldre-fornsvenska/sodermannalagen/. Tryckt SSGL-sida att bekräftas mot scan (Band IV via Internet Archive; ej på Commons). Osäkra glosor: lyð, kununx fall, viþer waro mæn, vtgierþ.'),

  ('Södermannalagen', 2,
   'Konungabalken (Kunungx balkær), flock XI — "Vm roþa ræt"',
   'Vm roþa ræt. XI.
COmber skip vtan warþ oc wacu. þa wari þet i fullum roþa ræt. Stiæl man a skipi minnæ æn half mark. böte III. marker til þrætskiptis. I. styremanni. andra malseghanda. þriþiæ hasætum allum. Stiæl half marka eller mera böte IX. marker til þræskiptis sum sagt ær. Slar man annæn eller sarghar. warin þa a comor gillæ at markum VI. Synis hwarte blat eller bloþoct. wari [bardaþi] (bardaghe) gilder at .III. markum. Warþer manni with oc ær ei sander at. wæri sic með .VI. mannum. þrim framman segl. oc þrim aptan. Sættæ þe þæssin mall mæþan þe vti æru með skipara witnum sex oc styrimanz. warin saclösir þa þe hem coma. Sættæs þe ei fyr. bötin þa sac eptir lanzlaghum hema. warþer man hoggin fullum sarum eller döþum dræpin. mæn kununger ær vti eller hans fult vm buð. þær bötis kunungi firi friþ brutit .XL. marker. Gierningæ þeræ liggin i gildi sinu æ halw dyrræ æn þa þet hema wari giort. skiptin þe bot. styriman. malseghande oc hasæter aller.
§. 1. ¶ Caster man annæn meþ wilia vtbyrþis i haf. æru til .II. manna witni. af skiparum. böte III. marker firi þet borþ til lanz weth. Firi þet til hafs weth .VI. marker.',
   'Om roddens/skeppsfärdens rätt (roþa rätt). Kap. XI.
Kommer ett skepp (ut) utan vakt och vakthållning (dvs. på ledungsfärd), då gälle för det full roþa rätt. Stjäl en man ombord mindre än en halv mark, böte tre mark till tredelning: en till styresmannen, en till målsäganden, en tredje till alla hasætar (roddare/besättningen). Stjäl han en halv mark eller mer, böte nio mark till tredelning som sagt. Slår en man en annan eller sårar honom, vare då slaget gillt (värderat) till sex mark. Syns varken blånad eller blod, vare slaget gillt till tre mark. Beskylls en man och är ej bunden (överbevisad) vid det, värje han sig med sex män — tre framför seglet (i fören) och tre akterut. Förlika de dessa mål medan de är ute (på färden), med sex skeppsmäns och styresmannens vittnen, vare de saklösa när de kommer hem. Förlikas de ej förr, böte då saken efter landslag hemma. Blir en man huggen med fulla sår eller dräpt till döds medan konungen är ute (med på färden) eller hans fullständiga sändebud, böte(s) till konungen för fridsbrott fyrtio mark. Deras gärningar ligge i sitt bötesvärde alltid hälften dyrare än om det gjorts hemma; dele boten styresmannen, målsäganden och alla hasætar.
§1. Kastar en man med vilja en annan överbord i havet, och finns två mäns vittnen bland skeppsmännen, böte tre mark för (avståndet till) det bord (relingen) mot land, (och) för det mot havssidan sex mark.',
   'On the law of the rowing / the sea-voyage (roþa rätt). Ch. XI.
When a ship puts out without watch and vigil (i.e. on ledung service), full "roþa rätt" applies to it. If a man steals aboard less than half a mark, he pays three marks in three parts: one to the steersman, one to the plaintiff, a third to all the hasætar (oarsmen/crew). Stealing half a mark or more: nine marks in three parts as stated. If a man strikes or wounds another, the blow is assessed at six marks. If neither bruise nor blood shows, the blow is assessed at three marks. If a man is accused and not convicted, he clears himself with six men — three fore of the sail and three aft. If they settle these matters while still at sea, with six shipmen''s and the steersman''s witness, they are free of liability when they come home. If not settled sooner, the case is paid at home under the land-law. If a man is struck with full wounds or slain while the king is out (on the voyage) or his full deputation, forty marks are paid to the king for breach of the peace. Their (penalties for) deeds stand always at half again the value they would have at home; the steersman, plaintiff, and all the hasætar divide the fine.
§1. If a man wilfully throws another overboard into the sea, and there are two shipmen as witnesses, he pays three marks for the board (gunwale) toward land, six marks for that toward the sea.',
   'Schlyter, SSGL band IV (Södermannalagen), 1838 — Konungabalken, flock XI ("Vm roþa ræt"). Digital verbatim-text: Fornsvenska textbanken (Holm B 53 / SSGL 4). Tryckt SSGL-sida att bekräftas mot scan. Osäker glosa: a comor (svårläst; trol. slagmärken) — obelagd tolkning.'),

  ('Skånelagen', 1,
   'Kap. 74 — enda leding-omnämnandet (fiskal pålaga på husætoft; INGEN ledings-organisation i lagtexten)',
   'Þættæ wiliæ summi men at loghum hauæ. fore þy at for husæ togt scal man leþing innæ oc stuæ reþe. ællær cumbær þæn illæ wiþær ær allæ skyldær scal vppe handæ fore husæ toftenæ oc ey meræ.',
   'Detta vill somliga män ha till lag, därför att för husplatsen (husætoften) skall man fullgöra leding och erlägga stuð (den kungliga stud-skatten); annars kommer den illa ut som skall bära alla skylder (pålagor) för husplatsen och ej mera. — Källkritisk not: leþing uppträder här enbart som FISKAL pålaga knuten till husætoft, parad med stuð, inne i rep-/jorddelningskapitlen. Ingen havne/hamna, ingen styrismand, inga skepps-/roderbestämmelser. Den danska ledings-ORGANISATIONEN (havne, skipæn, styrismand) är belagd i Kong Valdemars Jordebog och separata stadgar — INTE i den fornskånska lagtexten.',
   'Some men will have this for law, because for the house-plot (husætoft) one must render leding and pay the stud (royal tax); otherwise he fares ill who must bear all the dues for the house-plot and no more. — Source-critical note: here leþing appears only as a FISCAL charge tied to the house-plot, paired with stud, within the land-division chapters. No havne/hamna, no steersman, no ship or rowing provisions. The Danish leding ORGANISATION (havne, skipæn, styrismand) is attested in King Valdemar''s Land Register (Jordebog) and separate ordinances — NOT in the Old Scanian law text itself.',
   'Schlyter, SSGL band IX (Codex Iuris Scaniae / Skånelagen), Lund 1859 — kap. 74. Digital verbatim-text: Fornsvenska textbanken (Holm B 76 / SSGL 9). Facsimile: Commons File:Sveriges_Gamla_Lagar_IX_(1859).pdf. Ligaturen ﬁ→Þ normaliserad (ﬁættæ=Þættæ). Uttömmande termsökning: hafnæ/styrismand/snækkja/roþer = 0 belägg; leþing = 1 (detta kap.). Tryckt sida att bekräftas mot scan.')
) as v(law, ord, section_label, norse, sv, en, norse_source)
join public.historical_sources hs on hs.title = v.law
join lateral (select coalesce(max(stanza_no),0) mx from public.source_texts where source_id = hs.id) base on true;

-- 2) Östgötalagen: NEGATIVFYND (ingen grundtext att transkribera → original_norse NULL).
insert into public.source_texts
  (source_id, stanza_no, section_label, original_norse, translation_sv, translation_en, norse_source, sv_source, en_source, translation_kind)
select hs.id, coalesce((select max(stanza_no) from public.source_texts where source_id=hs.id),0) + 1,
   'Ledung — ej reglerad i bevarad text (ingen Konungabalk; leþung = 0 belägg)',
   null,
   'Ledung/flottorganisation regleras INTE i den bevarade Östgötalagen. Lagboken saknar Konungabalk; ordet leþung förekommer inte, och ledungstermerna hamna (roddardistrikt), roþer och styresman saknas. Konungens del gäller edsöre (fridsbrott), inte sjöuppbåd. Balkregister (verbatim ur texten): kristnu balkær · kunungx eþzsöre · drapa balkær · uaþa mal ok sara mal (hor, ran ok styld) · gipta balkær · ærfþa balkær · eghna salu · uinsorþa balkær · ræfsta balkær · bygda balkær. — Not: att institutionen ledung fanns i Östergötland historiskt är en ANNAN fråga (skilj institution från lagreglering); fyndet gäller enbart att den bevarade lagtexten inte reglerar den.',
   'Ledung / naval-levy organisation is NOT regulated in the preserved Östgötalagen. The lawbook has no King''s book; the word leþung does not occur, and the ledung terms hamna, roþer and styresman are absent. The king''s part concerns edsöre (breach-of-peace), not naval levy. Book register (verbatim from the text): Christian law · king''s edsöre · manslaughter · accident/wound (adultery, robbery, theft) · marriage · inheritance · land-sale · witness · prosecution · settlement. — Note: whether the ledung institution existed in Östergötland historically is a SEPARATE question (distinguish institution from statutory regulation); this finding is only that the preserved law text does not regulate it.',
   'Schlyter, SSGL band II (Codex Iuris Ostrogotici / Östgötalagen), 1830 — hela balkregistret. Digital verbatim-text: Fornsvenska textbanken (Holm B 50 / SSGL 2). Facsimile: Commons File:Sveriges_Gamla_Lagar_II_(1830).pdf. Negativfynd primärverifierat via termsökning (leþung = 0; ingen Konungabalk).',
   'Viking Age egen sammanfattning (negativfynd)', 'Viking Age own summary (negative finding)', 'egen'
from public.historical_sources hs where hs.title = 'Östgötalagen';
